#!/usr/bin/env python3

import sys
import json

def matches(s):
    return all([x in s for x in sys.argv[1:]])

data = json.load(sys.stdin)
filtered = [x for x in data["items"] if matches(x["match"])]

print(json.dumps({"items": filtered}))
