#!/usr/bin/env python3

import sys
import json

term = sys.argv[1]
data = json.load(sys.stdin)
filtered = [x for x in data["items"] if f"{term}" in x["match"]]

print(json.dumps({"items": filtered}))
