#!/usr/bin/env python3

import re
import os
import sys
import json
import sqlite3
import logging
from signal import signal, SIGINT, SIG_DFL as IGNORE

def v(h, k):
    return h[k] if k in h else None

signal(SIGINT, IGNORE)

logger = logging.getLogger(__name__)
logging.basicConfig(
    stream=sys.stdout,
    format='[%(asctime)s] %(levelname)s * %(message)s',
    level=logging.DEBUG if os.getenv("DEBUG") else logging.ERROR)

data = json.load(sys.stdin)
items = [(v(x,"title"), v(x,"arg"), v(x,"subtitle"), v(x,"match")) for x in data["items"]]

with sqlite3.connect("pins.sqlite3") as con:
    cur = con.cursor()
    cur.execute("DROP TABLE IF EXISTS pins")
    cur.execute("""
        CREATE VIRTUAL TABLE
        IF NOT EXISTS pins 
        USING FTS5(title, url, note, keywords)
    """)

    cur.executemany("""
        INSERT INTO pins(title, url, note, keywords)
        VALUES (?, ?, ?, ?)
    """, items)
